### ISSUE TITLE
Integration reports inaccurate data

### ISSUE THREAD

**Issue by prenetic** [emics/ham_radio_propagation#27]
When stations report N/A for a given value, GIRO presents as such (foe for example):

![image](https://github.com/emics/ham_radio_propagation/assets/11982895/d472d422-9915-41ac-810c-1168e742231f)

Which is also correctly displayed on prop.kc2g.com (no value displayed):

![image](https://github.com/emics/ham_radio_propagation/assets/11982895/9a413705-bf17-4806-a74d-ede56d48028c)

However the integration seems to be substituting this with 0.000:

![image](https://github.com/emics/ham_radio_propagation/assets/11982895/15de429b-4454-47d1-b6e8-c4943d32acef)

This is inaccurate, and causes lots of drops in graphs over time. Instead, the integration should simply report unavailable when a given value is reported N/A.

Given measurements are not available from all stations at all times, I've created aggregate template sensors that take nearby station data and handle gaps as a workaround. While cumbersome, this effectively takes the average of 1 or more datapoints, and if all datapoints are 0 the state will fail to render as you cannot average an empty list of values, and the sensor will correctly report unavailable.

```yaml
    - unique_id: sensor.ham_radio_propagation_solar_hf_foe_average
      attributes:
        friendly_name: Solar Data HF foE Average
      icon: mdi:format-wrap-inline
      unit_of_measurement: MHz
      state_class: measurement
      state: >
        {% set sensor_list = [
            states('sensor.ham_radio_propagation_solar_hf_foe_ga762') | float(default=0),
            states('sensor.ham_radio_propagation_solar_hf_foe_mhj45') | float(default=0),
            states('sensor.ham_radio_propagation_solar_hf_foe_pf765') | float(default=0)
          ]
        %}
        {{ sensor_list | reject('==', 0) | average | round(3) }}
```

Results with all sources shown:

![image](https://github.com/emics/ham_radio_propagation/assets/11982895/6199804a-35a6-4da0-8eb1-ab4dea62b516)

Average template sensor output with gaps coinciding with N/A:

![image](https://github.com/emics/ham_radio_propagation/assets/11982895/4e39ddfc-2961-4e7c-b768-3686807b1c2e)

Expected behavior would be for the integration to take care of this natively. If a station is reporting N/A, do not substitute a 0 value.
